import { Inter } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import BackgroundPattern from "@/components/BackgroundPattern";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, "relative overflow-x-hidden")}>
        {children}
        <BackgroundPattern />
      </body>
    </html>
  );
}
